#use swagger ui here - 
#http://localhost:8080/swagger-ui/index.html

#app name
spring.application.name=ibm-springboot-demo

#server port number 
server.port=8080

spring.data.mongodb.uri=mongodb://localhost:27017/ibm-ems
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=ibm-ems
spring.data.mongodb.auto-index-creation=true

# MongoDB driver logging
#logging.level.org.mongodb.driver=DEBUG

# Spring Data MongoDB internals
#logging.level.org.springframework.data.mongodb=DEBUG

# Spring Boot auto-configuration decisions (the most useful one)
#logging.level.org.springframework.boot.autoconfigure=DEBUG



#spring.application.name=ibm-springboot-demo
#
## --- MongoDB ---
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=ibm-ems
#spring.data.mongodb.auto-index-creation=true